name: Run suite tests

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request:
    branches:
      - main
      - 'v*'


jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Run unit tests
        run: npm test

  build-and-run-coverage:
    name: Check code coverage
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull_requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm i

      - name: Build code
        run: npm run build

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2